config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show, :index]

  get    'home'    => 'sessions#home'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get    'signup'  => 'users#new'

  resources :attendances, only: [:new, :create, :index, :show]

  get 'external_attendances', to: 'attendances#external_attendances', as:'external_attendances'
  resources :groups, only: [:new, :create, :index, :show] 

  root 'sessions#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  validates :name, length: { in: 4..30 }, uniqueness: { case_sensitive: false }
  validates :amount, numericality: { only_integer: true }

  belongs_to :author, class_name: 'User'
  belongs_to :group, optional: true

  def self.attn_with_group(current_user)
    Attendance.includes(:group).where.not(group: nil).where(author: current_user.id).order(created_at: :desc)
  end

  def self.attn_without_group(current_user)
    Attendance.includes(:group).where(group: nil, author: current_user.id).order(created_at: :desc)
  end

  def self.group_has_attn(group)
    Attendance.includes(:group).where(group_id: group.id).order(created_at: :desc)
  end

  def self.current_user_groups_id(current_user_id)
    groups = Attendance.joins(:group).select(:group_id).where(author_id: current_user_id).group(:group_id)
    groups_id = []
    groups.each { |g| groups_id << g.group_id }
    groups_id
  end

  def self.friends_name(current_user, other_users)
    g_id = Attendance.current_user_groups_id(current_user.id)
    Attendance.joins(:author).select(:author_id, 'users.name').where(group_id: g_id, author: other_users.ids)
      .group(:author_id, 'users.name')
  end
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, length: { in: 4..40 }, uniqueness: { case_sensitive: false }

  belongs_to :user
  has_many :attendances
  has_one_attached :group_avatar

  def self.group_alphabetical_order
    Group.order('lower(name) ASC').all
  end

  def self.attn_groups_by_user(user_id)
    Group.select(:name).where(id: user_id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, length: { in: 4..25 }, uniqueness: { case_sensitive: false }

  has_many :attendances, foreign_key: 'author_id', dependent: :destroy
  has_many :groups, dependent: :destroy
  has_one_attached :user_avatar

  def self.not_current_user_list(current_user)
    User.where.not(id: current_user.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  def new
    @attendance = Attendance.new
  end

  def create
    @attendance = current_user.attendances.new(attendance_params)
    if @attendance.save
      flash[:success] = 'Attendance created successfully.'
      redirect_to current_user
    else
      flash[:danger] = 'Attendance couldn\'t be created.'
      render 'new'
    end
  end

  def index
    @attendances = Attendance.attn_with_group(current_user)
  end

  def show; end

  def external_attendances
    @attendances = Attendance.attn_without_group(current_user)
  end

  private

  def attendance_params
    params.require(:attendance).permit(:name, :amount, :group_id)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  include GroupsHelper
  def new
    @group = Group.new
  end

  def create
    @group = current_user.groups.new(group_params)
    @group.group_avatar.attach(group_params[:group_avatar])
    if @group.save
      flash[:success] = 'Group created successfully.'
    else
      flash[:danger] = 'Group could not be created.'
    end
    redirect_to groups_path
  end

  def index
    @groups = Group.group_alphabetical_order
  end

  def show
    @group = Group.where(id: params[:id]).first
  end

  private

  def group_params
    params.require(:group).permit(:user_id, :name, :group_avatar)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def home; end

  def create
    user = User.find_by(name: session_params[:name])
    if user
      log_in(user)
      flash[:success] = 'You have successfully logged in.'
      redirect_to user
    else
      flash.now[:danger] = 'You could not log in. Invalid name.'
      render 'new'
    end
  end

  def destroy
    log_out
    if session[:user_id].nil?
      flash.now[:success] = 'You have successfully logged out.'
      render 'home'
    else
      flash[:danger] = 'There was an error while loggin out.'
      session_redirect
    end
  end

  private

  def session_params
    params.require(:session).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.user_avatar.attach(user_params[:user_avatar])

    if @user.save
      log_in(@user)
      flash[:success] = 'User successfully created.'
      redirect_to @user
    else
      flash[:danger] = 'The user could not be created.'
      redirect_to new_user_path
    end
  end

  def show
    @user = current_user
  end

  def index
    @users = User.not_current_user_list(current_user)
  end

  private

  def user_params
    params.require(:user).permit(:name, :user_avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
  def attn_group(group_id)
    # rubocop:disable Style/GuardClause
    if group_id
      image = Group.where(id: group_id).first
      if image.group_avatar.attached?
        image_tag image.group_avatar, class: 'group-avatar border'
      else
        image_tag 'default_group_avatar.png', class: 'group-avatar d-block border'
      end
    end
    # rubocop:enable Style/GuardClause
  end

  def total_attn(attendances)
    total = 0
    attendances.each { |a| total += a.amount }
    total
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
  def group_user_name(user_id)
    User.find_by_id(user_id).name
  end

  def group_avatar(group)
    if group.group_avatar.attached?
      image_tag group.group_avatar, class: 'group-avatar d-block border'
    else
      image_tag 'default_group_avatar.png', class: 'group-avatar d-block border'
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def user_avatar(user)
    u = user
    u = User.find_by_id(user) unless user.is_a? User
    if u.user_avatar.attached?
      image_tag u.user_avatar
    else
      image_tag 'default_user_avatar.png', class: 'avatar'
    end
  end
end

app/views/attendances/_attendances.html.erb
<div class="attn-list-section">
  <section>
    <div>
      Total:
    </div>
    <div>
      <%= total_attn(@attendances) %> 
    </div>
  </section>

  <% @attendances.each do |item| %>
    <article class="art-attn border-art">
      <div class="group-avatar">
        <%= attn_group(item.group_id) %>
      </div>

      <div class="attn-description">  
        <div>
          Name:
          <%= item.name %>
        </div>
        
        <div>
          Created at:
          <%= item.created_at.strftime("%Y/%m/%d") %>
        </div>
      </div>

      <div> 
        Qty:
        <%= item.amount %>
      </div>  
    </article>
  <% end %>
</div>

<%= link_to 'ADD NEW ATTENDANCE', new_attendance_path, class: 'add-new-button' %>

app/views/attendances/external_attendances.html.erb
<div class="container">
  <div class="attn-container">
    <div>
    <header class="header header-bg">
      <%= link_to image_tag("arrow_left.png"), user_path(current_user.id)%>
      
      <div class="col-7">
        <h1 class="m-0 title">EXTERNAL ATTN</h1>
      </div>

      
      <%= render partial: 'sessions/logout_link'%>
    </header>
  </div>

  <section class="attn-render">
    <%= render 'attendances' %>          
  </section>
</div>

app/views/attendances/index.html.erb
<div class="container">
  <div class="attn-container">
    <div>
      <header class="header header-bg">
        <%= link_to image_tag("arrow_left.png"), user_path(current_user.id)%>
          
        <div>
          <h1>ATTENDANCES</h1>
        </div>

        <%= render partial: 'sessions/logout_link'%>
      </header>
    </div>

    <section class="attn-render">
      <%= render 'attendances' %>          
    </section>
  </div>
</div>

app/views/attendances/new.html.erb
<div class="container">
  <div>
    <header class="header header-bg">
      <%= link_to image_tag("arrow_left.png"), attendances_path %>

      <div class="">
        <h1 class="">NEW ATTENDANCE</h1>
      </div>

      <input type="submit" value="Save" form="new_attn_form">      
  </header>

  <section class="login-form attn-form">
    <%= form_for(@attendance, html: {id: 'new_attn_form'}) do |form| %>
      <%= form.text_field :name, placeholder: 'Attendance\'s Name' %><br><br>

      <div>
        <%= form.label :select_quantity %><br>
        <%= form.select :amount, (1..10) %><br><br>
      </div>

      <% groups = Group.all %>
      <div>
        <%= form.label :select_group %><br>
        <%= form.select :group_id, groups.map{|g| [g.name, g.id] }, include_blank: 'No Group' %><br>
      </div>
    <% end %>
  </section> 
</div>

app/views/groups/index.html.erb
<div class="container profile-bg">
  <div class="attn-container">
    <div>
      <header class="header">
        <%= link_to image_tag("arrow_left.png"), user_path(current_user.id)%>
        
        <div>
          <h1>GROUPS</h1>
        </div>

        <%= render partial: 'sessions/logout_link'%>      
      </header>
    </div>    

    <section class="attn-render">
      <div class="attn-list-section">
        <% @groups.each do |g| %>
          <article class="art-group border-art">
            <span class="group-avatar">
              <%= group_avatar(g) %>
            </span>

            <div class="attn-description">
              <div>
                Name: <%= link_to "#{g.name}", group_path(@group, id: g.id) %>
              </div>
              <div>
                Created At:
                <%= g.created_at.strftime("%Y/%m/%d") %>
              </div>
            </div>  
          </article>
        <% end %>
      </div>      
      
      <%= link_to 'CREATE A GROUP', new_group_path, class: 'add-new-button' %>
    </section>     
  </div>
</div>

app/views/groups/new.html.erb
<div class="container">
  <div class="container-reg-log">
    <header class="header header-bg">
      <%= link_to image_tag("arrow_left.png"), user_path(current_user.id) %>
      
      <div>
        <h1 class=>NEW GROUP</h1>
      </div>

      <input type="submit" value="Save" form="new_group_form">
    </header>
  

    <section class="login-form">
      <%= form_for(@group, html: {id: 'new_group_form'}) do |form| %>
        <%= form.text_field :name, placeholder: 'Group\'s Name' %><br>
        <%= form.file_field :group_avatar %><br><br>
      <% end %>     
    </section>
  </div>
</div>

app/views/groups/show.html.erb
<div class="container">
  <div class="attn-container">
    <div>
      <header class="header header-bg">
        <%= link_to image_tag("arrow_left.png"), groups_path %>

        <div>
          <h1 class="m-0 title">GROUP</h1>
        </div>
        
        <%= render partial: 'sessions/logout_link'%>
        </div>
      </header>
      
      <section class="show-group">
        <h2>
          <%= @group.name %>
        </h2>
        <h3>ATTENDANCES:</h3>
        
        <% Attendance.group_has_attn(@group).each do |a| %>
          <article class="border-art">
            <div>
              Name:
              <%= a.name %>
              <div>
                Author Name:
                <%= group_user_name(a.author_id)%>
              </div>
              <div>
                Created at:
                <%= a.created_at.strftime("%Y/%m/%d") %>
              </div>
            </div>
          </article> 
        <% end %>
      </section>
    </div>
  </div>
</div>

 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCapstoneProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>    
    <%= yield %>    
  </body>
</html>

app/views/users/index.html.erb
<div class="container profile-bg">
  <div class="attn-container">
    <div>
      <header class="header">
        <%= link_to image_tag("arrow_left.png"), user_path(current_user.id)%>
        
        <div>
          <h1 class="m-0 title">USERS</h1>
        </div>
        
        <%= render partial: 'sessions/logout_link'%>      
      </header>
    </div>

    <section class="attn-render">
      <div class="attn-list-section">
        <% Attendance.friends_name(current_user, @users).each do |user| %>
          <article class="art-group border-art">
            <div>
              <span class="group-avatar">
                <%= user_avatar(user.author_id) %>
              </span>
            </div>

            <div class="attn-description">
              <div>
                <strong>Name:</strong>
                <%= user.name %>
              </div>
              
              <strong>Groups in common:</strong>
              <ol>                
                <% Group.attn_groups_by_user(Attendance.current_user_groups_id(user.author_id)).each do |g| %>
                  <li>
                    <%= g.name %>
                  </li>
                <% end %>
              </ol>
            </div>
          </article>
        <% end %>
      </div>
    </section>     
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="container-reg-log">
    <header class="header header-bg">
      <%= link_to image_tag("arrow_left.png"), root_path %>
      
      <div>
        <h1>REGISTER</h1>
      </div>
      
      <input type="submit" value="Next" form="register">
    </header>
  
    <section class="login-form">
      <%= form_for(@user, url: users_path, html: {id: 'register'}) do |f| %>
        <%= f.file_field :user_avatar, placeholder: 'Upload Picture' %><br><br>

        <%= f.text_field :name, placeholder: 'Name' %><br><br>
      <% end %>
    </section>
  </div>
</div>

app/views/users/show.html.erb
<div class="container profile profile-bg">    
  <header>
    <div>
      <div>
        <%= render partial: 'sessions/logout_link' %>
      </div>        
    </div>
    <span class="avatar">
      <%= user_avatar(@user) %>
    </span>
    
    <h1><%= @user.name%></h1>
  </header>

  <section>
    <ul>
      <li id="all_attn">
        <div class="menu-border">
          <%= link_to 'All my Attendances', attendances_path %><br> 
        </div> 
      </li>         
      <li id="all_ext_attn">
        <div class="menu-border">
          <%= link_to 'All my External Attendances', external_attendances_path %><br>
        </div>
      </li>
      <li id="all_groups">
        <div class="menu-border">
          <%= link_to 'All Groups', groups_path %>
        </div>  
      </li>
      <li id="all_users">
        <%= link_to 'Bar Hopping Users', users_path %>
      </li>  
    </ul>      
  </section> 
</div>